routes/web.php
<?php


use App\Http\Controllers\DemoController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
/*
Route::get('/{nom}', function($n){
    Return "Bonjour <strong>$n</strong>";
});*/
Route::get('/{nom}', [HomeController::class, 'home']);

Route::prefix('admin')->group(function(){
    Route::resource("categories", CategoryController::class)
                                    ->except(['show'])
                                    ->names('categories');
});


Route::get('/demo/{id}',[DemoController::class, "voir"])->name("demo");
Route::get("about",[DemoController::class, "about"])->name('about');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name'];

    public function products() : HasMany
    {
        return $this->hasMany(Product::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Product extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'price',
        'image',
        'stock',
        'status'
    ];

    public function category    () : BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}

app/Models/TodoList.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TodoList extends Model
{
    use HasFactory;
}

app/Models/Todolist2.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todolist2 extends Model
{
    use HasFactory;

    protected $fillable = [
        'texte',
        'termine'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::orderby('id','desc')->paginate(5);

        //dd($categories);

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
           'name' => 'required' 
        ]);

        Category::create($validated);

        return redirect()->route('categories.index')
            ->with('success', 'Catégorie ajoutée avec succès !');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {

        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Category $category)
    {
        $validated = $request->validate([
            'name' => 'required'
        ]);

        $category->update($validated);

        return redirect()->route('categories.index')
            ->with('success', 'Catégorie modifiée avec succès !');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {

        if($category->id == 2){
            return redirect()->route('categories.index')
            ->with('failed', 'Impossible de supprimer la catégorie par défaut');
        }

        $products = $category->products ;
        //dd($products);

        foreach ($products as $product) {
            $product->category_id = 2;
            $product->save();
        }

        $category->delete();

        return redirect()->route('categories.index')
            ->with('success', 'Catégorie supprimé avec succès !');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/DemoController.php
<?php

namespace App\Http\Controllers;

use App\Models\TodoList;
use Illuminate\Http\Request;

class DemoController extends Controller
{
    public function voir(Request $request, $id){

        return view("demo", compact("id"));
    }

    public function about(){
        
        return view("about");
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function home($nom){
        return view('home',compact('nom'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/about.blade.php
@extends('layout')

@section('title', "A propos de LGI3")

@section("content")
<h1>A propos de LIG3</h1>
<p>

    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis labore molestias dolores aliquam omnis provident iure asperiores incidunt suscipit nisi aspernatur, et corporis sint nostrum aut ratione! Cupiditate, autem ea.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum dolorum doloremque temporibus dolores ea tempore expedita. Unde natus sapiente placeat error est, rerum, sint, iure illum quia quam consequatur veritatis.
</p>

<p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, deserunt cupiditate eveniet tenetur saepe porro doloremque iure culpa magnam ex, ipsa neque ipsam suscipit maiores dolores sapiente, sequi distinctio dolore?
    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque, vel doloribus. Dignissimos, sit? Dolorum ut assumenda dolorem cum minima laudantium consectetur atque, asperiores provident quos dolores amet tempore, eligendi debitis.
</p>
@endsection

resources/views/categories/create.blade.php
@extends('layout')

@section('title', "Formulaire d'ajout d'une nouvelle catégorie")

@section('content')
    <h3>Formulaire d'ajout d'une nouvelle catégorie</h3>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('categories.store') }}" method="post">
        @csrf
        @include('categories.form')
        <div class="d-grid gap-2">
            <button class="btn btn-success">
                Ajouter une nouvelle catégorie
            </button>
            <a href="{{ route('categories.index') }}" class="btn btn-secondary">
                Annuler la création de nouvelle catégorie
            </a>
        </div>
    </form>

@endsection

resources/views/categories/edit.blade.php
@extends('layout')

@section('title', "Modification d'une catégorie")

@section('content')
    <h3>Modification de la catégorie : 
        <strong>{{ $category->name }}</strong>
    </h3>
    <form action="{{ route('categories.update', $category->id) }}" 
        method="post">

        @csrf
        @method('PUT')
        @include('categories.form')
        
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-warning">
                Modifier la catégorie
            </button>
            <a href="{{ route('categories.index') }}" 
                class="btn btn-secondary">
                Annuler la modification
            </a>
        </div>
    </form>
@endsection

resources/views/categories/form.blade.php
<div class="form-floating mb-3">
    <input 
        value="@isset($category->name) {{ $category->name }} @endisset"
        required type="text" class="form-control" 
            id="name" name="name" placeholder="Ex : Cosmétiques">
    <label for="name">
        Nom de la catégorie
    </label>
</div>

resources/views/categories/index.blade.php
@extends("layout")

@section('title', "La liste des categories")

@section('content')<
    <h3>La liste des articles</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{{ route('categories.create') }}" class="btn btn-primary">
            Ajouter une nouvelle catégorie d'article
        </a>
    </div>
    @if (Session::has('success'))
        <div class="alert alert-success">
            {{ Session::get('success') }}
        </div>
    @endif

    @if (Session::has('failed'))
        <div class="alert alert-danger">
            {{ Session::get('failed') }}
        </div>
    @endif
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nom de la catégories</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($categories as $category)
                <tr>
                    <td>{{ $category->name }}</td>
                    <td class="d-inline-flex gap-1">
                        <a class="btn btn-warning btn-sm" 
                        href="{{ route('categories.edit',$category->id) }}">
                            Modifier
                        </a>
                        <form action="{{ route("categories.destroy", $category->id) }}" 
                                method="post">
                                @csrf
                                @method("DELETE")
                                <button onclick="return confirm('Êtes-vous sûr ?')"
                                type="submit" class="btn btn-danger btn-sm">
                                    Supprimer
                                </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="position-relative mt-5">
        <div class="position-absolute top-0 start-50 translate-middle">
             {{ $categories->links() }}
        </div>
    </div>

@endsection

resources/views/demo.blade.php
@extends('layout')

@section("title", "Demo")

@section("content")
<h1>Bienvenue sur ma vue Démo</h1>

<strong>Identifiant : </strong> {{ $id }}

<a href="{{ route('about') }}">A propos de LGI3</a>
@endsection

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bienvenue sur mon site</title>
</head>
<body>
    Bonjour <strong>{{  $nom }}</strong>
</body>
</html>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title') | LGI3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <header>
        @include('partials.header')
    </header>
    <main class="container mt-3">
        @yield('content')
    </main>
    <footer>
        @include('partials.footer')
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

resources/views/partials/header.blade.php
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">LGI Commerce</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>